
review_title: Test Review
effect_measure: SMD
pico:
  population: Test Population
  intervention: Test Intervention
  comparator: Test Comparator
  outcome: Test Outcome
inclusion_criteria:
  - RCT
exclusion_criteria:
  - Non-RCT
