review_title: Effect of Cognitive-Behavioral Therapy on Pain
effect_measure: SMD
pico:
  population: Adults with fibromyalgia
  intervention: Cognitive-Behavioral Therapy
  comparator: Placebo or active comparator
  outcome: Pain intensity at post intervention
pubmed_query_cleaned: Adults with fibromyalgia AND Cognitive-Behavioral Therapy AND
  Pain intensity AND randomized controlled trial[pt]
inclusion_criteria:
- RCT
- Adult participants
exclusion_criteria:
- Non-RCT
- Animal studies
